version: "3"

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TokyoJoe138!
    volumes:
      - mongo-data:/data/db


  mongo-express:
    image: mongo-express:latest
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=TokyoJoe138!
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: always

  keycloak:
      image: quay.io/keycloak/keycloak:18.0.2
      command: ["start-dev", "--import-realm"]
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: TokyoJoe138!
        KC_REALM_NAME: "hypertheory"
      volumes:
        - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro
      ports:
        - 8080:8080



      
volumes:
  mongo-data:


networks:
  registrations:
  